import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { uuid } from 'uuidv4';

export async function getStaticProps(context) {
  const result = await fetch(`https://hot-walls-sing-186-225-235-50.loca.lt/static/${uuid()}`).then(res => res.json());

  return {
    props: { content: result.message },
    revalidate: 120
  }
}

export default function Home({ content }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {content}
        </h1>
      </main>
    </div>
  )
}